images = [
    ["1.png", "serous", "clotted", "lymphatic"],
    ["2.png", "bilious", "clotted", "biliary"],
    ["3.png", "feculent", "thin/watery", "pancreatic"],
    ["4.png", "chylous", "thick/viscous", "lymphatic"],
    ["5.png", "serosanguineous", "clotted", "hemorrhagic"],
    ["6.png", "serous", "clotted", "lymphatic"],
    ["7.png", "serous", "oily", "lymphatic"],
    ["8.png", "serous", "oily", "lymphatic"],
    ["9.png", "chylous", "clotted", "enteric"],
    ["10.png", "feculent", "clotted", "enteric"],
    ["11.png", "serous", "mucous", "lymphatic"],
    ["12.png", "hemorrhagic", "thin/watery", "pancreatic"],
    ["13.png", "serous", "clotted", "lymphatic"],
    ["14.png", "bilious", "clotted", "lymphatic"],
    ["15.png", "bilious", "mucous", "biliary"],
    ["16.png", "serous", "thick/viscous", "enteric"],
    ["17.png", "serous", "clotted", "hemorrhagic"],
]